name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm start
    - name: Deploy to Render
      run: |
        npm install -g render-cli
        render-cli deploy --service-name your-render-service-name --api-key ${{ secrets.RENDER_KEY }}
